apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: pushkal26/first-nodejs:latest  # Replace this with your Docker Hub image
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
